GRAMMAR_EXERCISES = {
    1: {
        "grammar": [
            {"type": "multiple_choice", "q": "اختر أداة الاستفهام: «ـــــ اسمُكَ؟»", "answer": "ما", "options": ["ما", "أين", "هل", "متى"], "hint": "للسؤال عن الأسماء"},
            {"type": "multiple_choice", "q": "«ـــــ أنتَ؟» (السؤال عن البلد)", "answer": "من أين", "options": ["من أين", "ما", "كيف", "هل"], "hint": "للمكان"},
            {"type": "multiple_choice", "q": "اسم الإشارة للمذكر: «ـــــ خالد»", "answer": "هذا", "options": ["هذا", "هذه", "ذلك", "تلك"], "hint": "للمذكر القريب"},
            {"type": "multiple_choice", "q": "اسم الإشارة للمؤنث: «ـــــ فاطمة»", "answer": "هذه", "options": ["هذه", "هذا", "ذلك", "هؤلاء"], "hint": "للمؤنث القريب"},
            {"type": "true_false", "q": "«هل» أداة استفهام للإجابة بنعم أو لا.", "answer": "صحيح"},
            {"type": "true_false", "q": "نستخدم «هذا» للمؤنث.", "answer": "خطأ"},
            {"type": "fill_blank", "q": "أكمل: «ـــــ حالُكَ؟»", "answer": "كيف", "hint": "السؤال عن الحال"},
            {"type": "fill_blank", "q": "أكمل: «ـــــ جنسيتُكَ؟»", "answer": "ما", "hint": "للأشياء"},
            {"type": "multiple_choice", "q": "أيّ جملة صحيحة للتعريف بالنفس؟", "answer": "اسمي خالد", "options": ["اسمي خالد", "اسم خالد", "أنا اسمي هو", "خالد اسمي أنا"], "hint": "الصيغة البسيطة"},
            {"type": "true_false", "q": "«من أين أنت؟» سؤال عن البلد.", "answer": "صحيح"},
        ],
        "final_test": [
            {"type": "multiple_choice", "q": "[اختبار] معنى «السلامُ عليكم»؟", "answer": "Selamün aleyküm", "options": ["Selamün aleyküm", "Günaydın", "Hoşça kal", "Teşekkürler"]},
            {"type": "multiple_choice", "q": "[اختبار] الإشارة في «هذه طالبةٌ»:", "answer": "هذه", "options": ["هذه", "هذا", "طالبة", "في"]},
            {"type": "multiple_choice", "q": "[اختبار] الرد على «كيف حالك؟»", "answer": "بخير والحمد لله", "options": ["بخير والحمد لله", "من تركيا", "اسمي خالد", "نعم"]},
            {"type": "true_false", "q": "[اختبار] «وعليكم السلام» رد التحية.", "answer": "صحيح"},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «أنا ـــــ تركيا»", "answer": "من", "hint": "حرف جر"},
            {"type": "multiple_choice", "q": "[اختبار] «ثلاثة» بالتركية:", "answer": "üç", "options": ["üç", "iki", "beş", "dört"]},
            {"type": "true_false", "q": "[اختبار] «نعم» تعني evet.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] أيّ كلمة تعني «الجنسية»؟", "answer": "الجنسية", "options": ["الجنسية", "البلد", "الاسم", "التحية"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «ـــــ هذا؟»", "answer": "من", "hint": "للعاقل"},
            {"type": "true_false", "q": "[اختبار] «هذا» للمذكر و«هذه» للمؤنث.", "answer": "صحيح"},
        ],
    },
    2: {
        "grammar": [
            {"type": "multiple_choice", "q": "الضمير: «ـــــ طالبٌ» (مذكر غائب)", "answer": "هو", "options": ["هو", "هي", "أنت", "أنا"], "hint": "الغائب المذكر"},
            {"type": "multiple_choice", "q": "الضمير: «ـــــ طالبةٌ» (مؤنثة غائبة)", "answer": "هي", "options": ["هي", "هو", "أنتِ", "هم"], "hint": "الغائبة المؤنثة"},
            {"type": "multiple_choice", "q": "أيّ الكلمات مؤنثة؟", "answer": "أخت", "options": ["أخت", "أخ", "جد", "عم"], "hint": "تاء التأنيث"},
            {"type": "multiple_choice", "q": "أيّ الكلمات مذكرة؟", "answer": "جد", "options": ["جد", "جدة", "أخت", "خالة"], "hint": "الخالية من التأنيث"},
            {"type": "true_false", "q": "«أنتَ» للمذكر و«أنتِ» للمؤنثة.", "answer": "صحيح"},
            {"type": "true_false", "q": "كلمة «أب» مؤنثة.", "answer": "خطأ"},
            {"type": "fill_blank", "q": "أكمل: «محمدٌ ـــــ أخي»", "answer": "هو", "hint": "ضمير مذكر غائب"},
            {"type": "fill_blank", "q": "أكمل: «فاطمةُ ـــــ أختي»", "answer": "هي", "hint": "ضمير مؤنثة غائبة"},
            {"type": "multiple_choice", "q": "مذكر كلمة «الأم»؟", "answer": "الأب", "options": ["الأب", "الأخت", "الجدة", "العمة"], "hint": "الوالد"},
            {"type": "true_false", "q": "«العم» أخو الأب و«الخال» أخو الأم.", "answer": "صحيح"},
        ],
        "final_test": [
            {"type": "multiple_choice", "q": "[اختبار] «الجد» بالتركية؟", "answer": "dede", "options": ["dede", "baba", "amca", "kardeş"]},
            {"type": "multiple_choice", "q": "[اختبار] «الأخت» بالتركية؟", "answer": "kız kardeş", "options": ["kız kardeş", "erkek kardeş", "anne", "teyze"]},
            {"type": "true_false", "q": "[اختبار] «الخالة» تعني teyze.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] الضمير: «ـــــ معلمةٌ»", "answer": "هي", "options": ["هي", "هو", "أنت", "هم"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «هذا جدّي وهذه ـــــ»", "answer": "جدتي", "hint": "مؤنث الجد"},
            {"type": "multiple_choice", "q": "[اختبار] «سبعة» بالتركية:", "answer": "yedi", "options": ["yedi", "altı", "sekiz", "dokuz"]},
            {"type": "true_false", "q": "[اختبار] «العم» (amca) أخو الأب.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] معنى «المطبخ»؟", "answer": "mutfak", "options": ["mutfak", "oda", "banyo", "ev"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «ـــــ بيتي»", "answer": "هذا", "hint": "إشارة للمذكر"},
            {"type": "true_false", "q": "[اختبار] كلمة «غرفة» مؤنثة.", "answer": "صحيح"},
        ],
    },
    3: {
        "grammar": [
            {"type": "multiple_choice", "q": "أيّ فعل مضارع؟", "answer": "يسكن", "options": ["يسكن", "سكن", "اسكن", "ساكن"], "hint": "حروف المضارعة"},
            {"type": "multiple_choice", "q": "حرف المضارعة في «أذهب»:", "answer": "الهمزة", "options": ["الهمزة", "الياء", "النون", "التاء"], "hint": "أنيت"},
            {"type": "multiple_choice", "q": "الترتيبي: «الدور ـــــ» (2)", "answer": "الثاني", "options": ["الثاني", "الأول", "الثالث", "الرابع"]},
            {"type": "multiple_choice", "q": "أداة السؤال عن العدد:", "answer": "كم", "options": ["كم", "ماذا", "متى", "أين"], "hint": "الكمية"},
            {"type": "true_false", "q": "«يكتب» فعل مضارع.", "answer": "صحيح"},
            {"type": "true_false", "q": "حروف المضارعة: أ ن ي ت.", "answer": "صحيح"},
            {"type": "fill_blank", "q": "أكمل: «ـــــ غرفةً في الشقة؟»", "answer": "كم", "hint": "عن الكمية"},
            {"type": "fill_blank", "q": "حوّل لمضارع: «كتب» ← ـــــ", "answer": "يكتب", "hint": "حرف المضارعة"},
            {"type": "multiple_choice", "q": "الترتيبي الأول للمذكر:", "answer": "الأول", "options": ["الأول", "الواحد", "أحد", "واحد"]},
            {"type": "true_false", "q": "«ماذا» نسأل بها عن الحدث.", "answer": "صحيح"},
        ],
        "final_test": [
            {"type": "multiple_choice", "q": "[اختبار] «الشقة» بالتركية؟", "answer": "daire", "options": ["daire", "oda", "kat", "ev"]},
            {"type": "multiple_choice", "q": "[اختبار] «الإيجار»؟", "answer": "kira", "options": ["kira", "kapı", "pencere", "masa"]},
            {"type": "true_false", "q": "[اختبار] «الدور» تعني kat.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] «الجمعة»؟", "answer": "Cuma", "options": ["Cuma", "Pazar", "Salı", "Perşembe"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «أسكنُ في الدور ـــــ» (3)", "answer": "الثالث", "hint": "الترتيبي 3"},
            {"type": "multiple_choice", "q": "[اختبار] «السرير»؟", "answer": "yatak", "options": ["yatak", "sandalye", "masa", "dolap"]},
            {"type": "true_false", "q": "[اختبار] «الكرسي» تعني sandalye.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] المضارع من «جلس»:", "answer": "يجلس", "options": ["يجلس", "جالس", "اجلس", "جلوس"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «ـــــ الإيجار؟»", "answer": "كم", "hint": "استفهام"},
            {"type": "true_false", "q": "[اختبار] «الأحد» أول الأسبوع.", "answer": "صحيح"},
        ],
    },
4: {
        "grammar": [
            {"type": "multiple_choice", "q": "أداة نفي المضارع:", "answer": "لا", "options": ["لا", "سـ", "قد", "هل"], "hint": "تنفي المضارع"},
            {"type": "multiple_choice", "q": "حرف الاستقبال القريب:", "answer": "سـ", "options": ["سـ", "لا", "ما", "هل"], "hint": "يتصل بالمضارع"},
            {"type": "multiple_choice", "q": "أداة السؤال عن الزمن:", "answer": "متى", "options": ["متى", "أين", "ما", "كيف"], "hint": "الوقت"},
            {"type": "multiple_choice", "q": "«ـــــ أذهبُ» (للنفي)", "answer": "لا", "options": ["لا", "سـ", "قد", "نعم"]},
            {"type": "true_false", "q": "«سأذهب» تفيد المستقبل.", "answer": "صحيح"},
            {"type": "true_false", "q": "«لا أشاهد التلفاز» منفية.", "answer": "صحيح"},
            {"type": "fill_blank", "q": "أكمل: «ـــــ تستيقظ؟»", "answer": "متى", "hint": "للزمن"},
            {"type": "fill_blank", "q": "أضف الاستقبال: «ـــــ أذهبُ غداً»", "answer": "سـ", "hint": "للمستقبل"},
            {"type": "multiple_choice", "q": "أداة السؤال عن المكان:", "answer": "أين", "options": ["أين", "متى", "كم", "ما"]},
            {"type": "true_false", "q": "«أين» للسؤال عن الزمان.", "answer": "خطأ"},
        ],
        "final_test": [
            {"type": "multiple_choice", "q": "[اختبار] «الفطور» بالتركية؟", "answer": "kahvaltı", "options": ["kahvaltı", "öğle yemeği", "akşam yemeği", "su"]},
            {"type": "multiple_choice", "q": "[اختبار] «يستيقظ»؟", "answer": "uyanır", "options": ["uyanır", "uyur", "yer", "gider"]},
            {"type": "true_false", "q": "[اختبار] «مبكراً» تعني erken.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] «السيارة»؟", "answer": "araba", "options": ["araba", "otobüs", "tren", "uçak"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «ـــــ أشاهدُ التلفاز»", "answer": "لا", "hint": "النفي"},
            {"type": "multiple_choice", "q": "[اختبار] «الخامس»:", "answer": "beşinci", "options": ["beşinci", "dördüncü", "altıncı", "üçüncü"]},
            {"type": "true_false", "q": "[اختبار] «الحافلة» تعني otobüs.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] المضارع من «قرأ»:", "answer": "يقرأ", "options": ["يقرأ", "قارئ", "اقرأ", "قراءة"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «ـــــ تذهب؟»", "answer": "أين", "hint": "للمكان"},
            {"type": "true_false", "q": "[اختبار] «سـ» حرف للاستقبال.", "answer": "صحيح"},
        ],
    },
    5: {
        "grammar": [
            {"type": "multiple_choice", "q": "المضارع للمؤنثة: «ماذا ـــــ؟» (أكل)", "answer": "تأكلين", "options": ["تأكلين", "تأكل", "يأكل", "آكل"], "hint": "ياء المخاطبة"},
            {"type": "multiple_choice", "q": "المضارع للمؤنثة من «تشرب»:", "answer": "تشربين", "options": ["تشربين", "يشرب", "أشرب", "نشرب"], "hint": "المخاطبة"},
            {"type": "multiple_choice", "q": "صيغة التعجب الصحيحة:", "answer": "ما هذا!", "options": ["ما هذا!", "ما هذا؟", "هذا ما", "ما هذه ما"], "hint": "بصيغة الاستفهام"},
            {"type": "true_false", "q": "«تأكلين» مضارع بياء المخاطبة.", "answer": "صحيح"},
            {"type": "true_false", "q": "«أحبُّ الشاي» جملة فعلية.", "answer": "صحيح"},
            {"type": "fill_blank", "q": "أكمل للمؤنثة: «هل ـــــ الشاي؟» (تحب)", "answer": "تحبين", "hint": "ياء المخاطبة"},
            {"type": "fill_blank", "q": "أكمل التعجب: «ـــــ هذا الطعام!»", "answer": "ما", "hint": "أداة تعجب"},
            {"type": "multiple_choice", "q": "نفي المضارع: «ـــــ آكل اللحم»", "answer": "لا", "options": ["لا", "سـ", "قد", "هل"]},
            {"type": "multiple_choice", "q": "المضارع للمذكر من «شرب»:", "answer": "تشرب", "options": ["تشرب", "تشربين", "يشرب", "نشرب"]},
            {"type": "true_false", "q": "«لا تأكل» للنهي.", "answer": "صحيح"},
        ],
        "final_test": [
            {"type": "multiple_choice", "q": "[اختبار] «الخبز» بالتركية؟", "answer": "ekmek", "options": ["ekmek", "et", "pirinç", "su"]},
            {"type": "multiple_choice", "q": "[اختبار] «اللحم»؟", "answer": "et", "options": ["et", "balık", "tavuk", "sebze"]},
            {"type": "true_false", "q": "[اختبار] «الماء» تعني su.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] «جوعان»؟", "answer": "aç", "options": ["aç", "susuz", "tok", "lezzetli"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل للمؤنثة: «ماذا ـــــ؟» (تشرب)", "answer": "تشربين", "hint": "ياء المخاطبة"},
            {"type": "multiple_choice", "q": "[اختبار] «الفاكهة»؟", "answer": "meyve", "options": ["meyve", "sebze", "salata", "süt"]},
            {"type": "true_false", "q": "[اختبار] «لذيذ» تعني lezzetli.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] «العصير»؟", "answer": "meyve suyu", "options": ["meyve suyu", "çay", "kahve", "süt"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل التعجب: «ـــــ هذا!»", "answer": "ما", "hint": "تعجب"},
            {"type": "true_false", "q": "[اختبار] «الشاي» تعني çay.", "answer": "صحيح"},
        ],
    },
    6: {
        "grammar": [
            {"type": "multiple_choice", "q": "حرف العطف في «الفجرُ والظهرُ»:", "answer": "الواو", "options": ["الواو", "الفاء", "ثم", "أو"], "hint": "الجمع"},
            {"type": "multiple_choice", "q": "فعل الأمر من «ذهب»:", "answer": "اذهب", "options": ["اذهب", "يذهب", "ذهب", "ذاهب"], "hint": "الطلب"},
            {"type": "multiple_choice", "q": "المبتدأ في «المسجدُ كبيرٌ»:", "answer": "المسجد", "options": ["المسجد", "كبير", "ال", "في"], "hint": "أول الجملة"},
            {"type": "multiple_choice", "q": "الخبر في «الصلاةُ عمودُ الدين»:", "answer": "عمود الدين", "options": ["عمود الدين", "الصلاة", "ال", "الدين"], "hint": "يكمل المبتدأ"},
            {"type": "true_false", "q": "«صلِّ» فعل أمر.", "answer": "صحيح"},
            {"type": "true_false", "q": "المبتدأ والخبر مرفوعان.", "answer": "صحيح"},
            {"type": "fill_blank", "q": "أكمل: «الفجرُ ـــــ الظهرُ صلاتان»", "answer": "و", "hint": "حرف عطف"},
            {"type": "fill_blank", "q": "فعل الأمر من «قرأ»: ـــــ", "answer": "اقرأ", "hint": "الطلب"},
            {"type": "multiple_choice", "q": "أداة السؤال عن السبب:", "answer": "لماذا", "options": ["لماذا", "متى", "أين", "كم"]},
            {"type": "true_false", "q": "«تعال معي» فيها فعل أمر.", "answer": "صحيح"},
        ],
        "final_test": [
            {"type": "multiple_choice", "q": "[اختبار] «الصلاة» بالتركية؟", "answer": "namaz", "options": ["namaz", "cami", "ezan", "abdest"]},
            {"type": "multiple_choice", "q": "[اختبار] «المسجد»؟", "answer": "cami", "options": ["cami", "namaz", "imam", "kıble"]},
            {"type": "true_false", "q": "[اختبار] «الوضوء» تعني abdest.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] «الفجر»؟", "answer": "sabah namazı", "options": ["sabah namazı", "öğle namazı", "ikindi namazı", "yatsı namazı"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «ـــــ معي» (أمر من تعال)", "answer": "تعال", "hint": "فعل أمر"},
            {"type": "multiple_choice", "q": "[اختبار] «الأذان»؟", "answer": "ezan", "options": ["ezan", "namaz", "secde", "rekat"]},
            {"type": "true_false", "q": "[اختبار] «المغرب» صلاة بعد الغروب.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] المبتدأ في «الإمامُ في المسجد»:", "answer": "الإمام", "options": ["الإمام", "المسجد", "في", "ال"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «المغربُ ـــــ العشاءُ»", "answer": "و", "hint": "عطف"},
            {"type": "true_false", "q": "[اختبار] «العصر» بعد الظهر.", "answer": "صحيح"},
        ],
    },
7: {
        "grammar": [
            {"type": "multiple_choice", "q": "حرف التخيير في «أقرأ كتاباً أو صحيفةً»:", "answer": "أو", "options": ["أو", "الواو", "الفاء", "ثم"], "hint": "الاختيار"},
            {"type": "multiple_choice", "q": "الماضي بتاء المتكلم من «درس»:", "answer": "درستُ", "options": ["درستُ", "أدرس", "ادرس", "دارس"], "hint": "تاء المتكلم"},
            {"type": "multiple_choice", "q": "«قريب من» عكسها:", "answer": "بعيد عن", "options": ["بعيد عن", "قريب إلى", "أمام", "خلف"]},
            {"type": "true_false", "q": "«درستُ» ماضٍ بتاء المتكلم.", "answer": "صحيح"},
            {"type": "true_false", "q": "«أو» حرف عطف للتخيير.", "answer": "صحيح"},
            {"type": "fill_blank", "q": "أكمل: «أدرس العربيةَ ـــــ الإنجليزيةَ»", "answer": "أو", "hint": "التخيير"},
            {"type": "fill_blank", "q": "الماضي بتاء المتكلم من «كتب»: ـــــ", "answer": "كتبتُ", "hint": "تاء المتكلم"},
            {"type": "multiple_choice", "q": "أداة السؤال عن الجامعة:", "answer": "في أيِّ", "options": ["في أيِّ", "متى", "كم", "هل"], "hint": "المكان المحدد"},
            {"type": "multiple_choice", "q": "الماضي من «يبدأ»:", "answer": "بدأ", "options": ["بدأ", "يبدأ", "ابدأ", "بادئ"]},
            {"type": "true_false", "q": "الماضي يدل على حدث انتهى.", "answer": "صحيح"},
        ],
        "final_test": [
            {"type": "multiple_choice", "q": "[اختبار] «الجامعة» بالتركية؟", "answer": "üniversite", "options": ["üniversite", "fakülte", "okul", "sınıf"]},
            {"type": "multiple_choice", "q": "[اختبار] «الامتحان»؟", "answer": "sınav", "options": ["sınav", "ödev", "ders", "kitap"]},
            {"type": "true_false", "q": "[اختبار] «المكتبة» تعني kütüphane.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] «الأستاذ»؟", "answer": "hoca", "options": ["hoca", "öğrenci", "kitap", "ders"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «ـــــ اللغةَ العربية» (ماضٍ بتاء المتكلم)", "answer": "درستُ", "hint": "تاء المتكلم"},
            {"type": "multiple_choice", "q": "[اختبار] «الرياضيات»؟", "answer": "matematik", "options": ["matematik", "tarih", "fen", "coğrafya"]},
            {"type": "true_false", "q": "[اختبار] «بعيد عن» عكس «قريب من».", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] حرف التخيير:", "answer": "أو", "options": ["أو", "و", "ثم", "ف"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «أدرسُ ـــــ جامعة؟»", "answer": "في أيِّ", "hint": "المكان"},
            {"type": "true_false", "q": "[اختبار] «الكلية» تعني fakülte.", "answer": "صحيح"},
        ],
    },
    8: {
        "grammar": [
            {"type": "multiple_choice", "q": "«ـــــ تعملُ في المستشفى؟»", "answer": "هل", "options": ["هل", "ما", "كم", "متى"], "hint": "نعم/لا"},
            {"type": "multiple_choice", "q": "الخبر المقدم في «لي أطفالٌ»:", "answer": "لي", "options": ["لي", "أطفال", "ال", "في"], "hint": "شبه الجملة المتقدم"},
            {"type": "multiple_choice", "q": "الماضي بتاء المتكلم من «عمل»:", "answer": "عملتُ", "options": ["عملتُ", "أعمل", "اعمل", "عامل"]},
            {"type": "true_false", "q": "«هل» جوابها نعم أو لا.", "answer": "صحيح"},
            {"type": "true_false", "q": "في «لي كتابٌ» الخبر مقدّم.", "answer": "صحيح"},
            {"type": "fill_blank", "q": "أكمل: «ـــــ لكِ أطفال؟»", "answer": "هل", "hint": "نعم/لا"},
            {"type": "fill_blank", "q": "الماضي بتاء المتكلم من «درس»: ـــــ", "answer": "درستُ", "hint": "تاء المتكلم"},
            {"type": "multiple_choice", "q": "معنى «أيضاً»:", "answer": "كذلك", "options": ["كذلك", "لا", "نعم", "ربما"], "hint": "المشاركة"},
            {"type": "multiple_choice", "q": "«كم ساعةً تعمل؟» تسأل عن:", "answer": "العدد", "options": ["العدد", "المكان", "الزمان", "السبب"]},
            {"type": "true_false", "q": "«أنا طبيبٌ أيضاً» تفيد المشاركة.", "answer": "صحيح"},
        ],
        "final_test": [
            {"type": "multiple_choice", "q": "[اختبار] «الطبيب» بالتركية؟", "answer": "doktor", "options": ["doktor", "mühendis", "öğretmen", "avukat"]},
            {"type": "multiple_choice", "q": "[اختبار] «المهندس»؟", "answer": "mühendis", "options": ["mühendis", "doktor", "hemşire", "muhasebeci"]},
            {"type": "true_false", "q": "[اختبار] «المستشفى» تعني hastane.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] «المعلم»؟", "answer": "öğretmen", "options": ["öğretmen", "öğrenci", "doktor", "avukat"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «ـــــ تعملُ هنا؟»", "answer": "هل", "hint": "نعم/لا"},
            {"type": "multiple_choice", "q": "[اختبار] «الشركة»؟", "answer": "şirket", "options": ["şirket", "büro", "okul", "dükkan"]},
            {"type": "true_false", "q": "[اختبار] «المحامي» تعني avukat.", "answer": "صحيح"},
            {"type": "multiple_choice", "q": "[اختبار] «الساعة»؟", "answer": "saat", "options": ["saat", "dakika", "gün", "yıl"]},
            {"type": "fill_blank", "q": "[اختبار] أكمل: «ـــــ ساعةً تعمل؟»", "answer": "كم", "hint": "العدد"},
            {"type": "true_false", "q": "[اختبار] «يومياً» تعني günlük.", "answer": "صحيح"},
        ],
    },
}
# ═══════════════════════════════════════════════════════════════════════
# الوحدات 9-16: تمارين متعاكسات/جمع/فهم (5 أسئلة فقط لكل وحدة)
# ═══════════════════════════════════════════════════════════════════════

GRAMMAR_EXERCISES.update({

    9: {  # التسوق
        "grammar": [],
        "final_test": [
            {"type": "multiple_choice", "q": "ما عكس «أبيض»؟", "answer": "أسود", "options": ["أسود", "أزرق", "أحمر", "أصفر"]},
            {"type": "multiple_choice", "q": "ما جمع «قميص»؟", "answer": "قمصان", "options": ["قمصان", "قميصات", "أقمصة", "قمائص"]},
            {"type": "multiple_choice", "q": "ما جمع «ثوب»؟", "answer": "أثواب", "options": ["أثواب", "ثيوب", "ثوبان", "ثوابات"]},
            {"type": "multiple_choice", "q": "ما العدد بين عشرين وأربعين؟", "answer": "ثلاثون", "options": ["ثلاثون", "خمسون", "ثمانون", "عشرون"]},
            {"type": "true_false", "q": "كلمة «المشتري» مذكَّرة.", "answer": "صَحِيح"},
        ],
    },

    10: {  # الجو
        "grammar": [],
        "final_test": [
            {"type": "multiple_choice", "q": "ما عكس «حر»؟", "answer": "برد", "options": ["برد", "دافئ", "معتدل", "مبلل"]},
            {"type": "multiple_choice", "q": "في أي فصل يكون الجو حاراً؟", "answer": "فصل الصيف", "options": ["فصل الصيف", "فصل الشتاء", "فصل الخريف", "فصل الربيع"]},
            {"type": "multiple_choice", "q": "ماذا نأخذ عندما تمطر؟", "answer": "مظلة", "options": ["مظلة", "خيمة", "شاطئ", "معطف"]},
            {"type": "multiple_choice", "q": "ما عكس «دافئ»؟", "answer": "بارد", "options": ["بارد", "حر", "معتدل", "مبلل"]},
            {"type": "true_false", "q": "نلبس المعطف في فصل الشتاء.", "answer": "صَحِيح"},
        ],
    },

    11: {  # الناس والأماكن
        "grammar": [],
        "final_test": [
            {"type": "multiple_choice", "q": "ما عكس «صحيح»؟", "answer": "خطأ", "options": ["خطأ", "كبير", "جميل", "بعيد"]},
            {"type": "multiple_choice", "q": "ما عكس «كبير»؟", "answer": "صغير", "options": ["صغير", "جميل", "بعيد", "قريب"]},
            {"type": "multiple_choice", "q": "أين تهبط الطائرة؟", "answer": "المطار", "options": ["المطار", "الجامعة", "المدينة", "البلد"]},
            {"type": "multiple_choice", "q": "من يدير الشركة؟", "answer": "المدير", "options": ["المدير", "الأصدقاء", "التاكسي", "المطار"]},
            {"type": "true_false", "q": "الرياض عاصمة المملكة العربية السعودية.", "answer": "صَحِيح"},
        ],
    },

    12: {  # الهوايات
        "grammar": [],
        "final_test": [
            {"type": "multiple_choice", "q": "أين نجد الكتب والمجلات؟", "answer": "المكتبة", "options": ["المكتبة", "المطار", "الشاطئ", "الفندق"]},
            {"type": "multiple_choice", "q": "ما الهواية التي تقوي الجسم؟", "answer": "الرياضة", "options": ["الرياضة", "القراءة", "المراسلة", "جمع الطوابع"]},
            {"type": "multiple_choice", "q": "ما هواية ركوب الخيل؟", "answer": "الفروسية", "options": ["الفروسية", "السباحة", "القراءة", "السفر"]},
            {"type": "multiple_choice", "q": "ما عكس «أكثر»؟", "answer": "أقل", "options": ["أقل", "كثير", "قليل", "مفيد"]},
            {"type": "true_false", "q": "القراءة هواية مفيدة.", "answer": "صَحِيح"},
        ],
    },

    13: {  # السفر
        "grammar": [],
        "final_test": [
            {"type": "multiple_choice", "q": "ما الذي نحتاجه للسفر إلى الخارج؟", "answer": "جواز السفر", "options": ["جواز السفر", "المفتاح", "الأمتعة", "الفندق"]},
            {"type": "multiple_choice", "q": "أين ننام عند السفر إلى مدينة بعيدة؟", "answer": "فندق", "options": ["فندق", "مطار", "طائرة", "تاكسي"]},
            {"type": "multiple_choice", "q": "ما عكس «تأشيرة الخروج»؟", "answer": "تأشيرة الدخول", "options": ["تأشيرة الدخول", "جواز السفر", "تذكرة", "إقامة"]},
            {"type": "multiple_choice", "q": "متى يجب أن نصل المطار قبل الإقلاع؟", "answer": "قبل ساعتين", "options": ["قبل ساعتين", "بعد ساعة", "بعد الإقلاع", "قبل خمس دقائق"]},
            {"type": "true_false", "q": "الطائرة أسرع وسيلة للسفر بين البلدان.", "answer": "صَحِيح"},
        ],
    },

    14: {  # الحج والعمرة
        "grammar": [],
        "final_test": [
            {"type": "multiple_choice", "q": "كم شوطاً نطوف حول الكعبة؟", "answer": "سبعة", "options": ["سبعة", "خمسة", "ثلاثة", "تسعة"]},
            {"type": "multiple_choice", "q": "أين يقف الحجاج يوم التاسع من ذي الحجة؟", "answer": "عرفات", "options": ["عرفات", "منى", "الكعبة", "المدينة"]},
            {"type": "multiple_choice", "q": "أين توجد الكعبة المشرفة؟", "answer": "المسجد الحرام", "options": ["المسجد الحرام", "المسجد النبوي", "منى", "المدينة"]},
            {"type": "multiple_choice", "q": "في أي شهر يؤدى الحج؟", "answer": "ذو الحجة", "options": ["ذو الحجة", "رمضان", "محرم", "شعبان"]},
            {"type": "true_false", "q": "الحج فريضة من أركان الإسلام.", "answer": "صَحِيح"},
        ],
    },

    15: {  # الصحة
        "grammar": [],
        "final_test": [
            {"type": "multiple_choice", "q": "من يعالج الأسنان؟", "answer": "طبيب الأسنان", "options": ["طبيب الأسنان", "طبيب الأنف", "المدير", "المريض"]},
            {"type": "multiple_choice", "q": "ماذا نقول للمريض؟", "answer": "شفاك الله", "options": ["شفاك الله", "مرحباً", "تفضل", "شكراً"]},
            {"type": "multiple_choice", "q": "ما الذي يخفف الألم؟", "answer": "دواء", "options": ["دواء", "حلوى", "أكل", "نوم"]},
            {"type": "multiple_choice", "q": "ما الذي نأخذه قبل زيارة الطبيب؟", "answer": "موعد", "options": ["موعد", "دواء", "حلوى", "كتاب"]},
            {"type": "true_false", "q": "أكل الحلوى الكثيرة يضر بالأسنان.", "answer": "صَحِيح"},
        ],
    },

    16: {  # العطلة
        "grammar": [],
        "final_test": [
            {"type": "multiple_choice", "q": "ما العيد الذي يأتي بعد رمضان؟", "answer": "عيد الفطر", "options": ["عيد الفطر", "عيد الأضحى", "عيد الميلاد", "عيد الاستقلال"]},
            {"type": "multiple_choice", "q": "في أي عيد نذبح الأضحية؟", "answer": "عيد الأضحى", "options": ["عيد الأضحى", "عيد الفطر", "رمضان", "ذو القعدة"]},
            {"type": "multiple_choice", "q": "ماذا نقول للمسلم في العيد؟", "answer": "عيدك مبارك", "options": ["عيدك مبارك", "شفاك الله", "مع السلامة", "في أمان الله"]},
            {"type": "multiple_choice", "q": "ما الشهر الذي نصوم فيه؟", "answer": "رمضان", "options": ["رمضان", "شعبان", "ذو الحجة", "محرم"]},
            {"type": "true_false", "q": "زكاة الفطر تُعطى للفقراء.", "answer": "صَحِيح"},
        ],
    },

})